### ISSUE TITLE
Self-closing tags minify /> to > breaks inline SVG

### ISSUE THREAD

**Issue by barlas** [murphydanger/gulp-minify-html#24]
Hello there,

When i convert my inline svg code with minify-html, it removes self-closing tags' slash "/" and this breaks drawing.

Is there a option which prevents removing slashes ?

Original code:
`<polygon fill="url(#SVGID_1_)" points="511.7,339 494.7,398.8 476.3,451.3 576.9,380.9612.3,322.8 574.3,326.3" />`

Minified output:
`<polygon fill=url(#SVGID_1_) points="511.7,339 494.7,398.8 476.3,451.3 576.9,380.9 612.3,322.8 574.3,326.3">`

**Comment by jonathanepollack** [comment]
Let `minimize` know about this.
