### ISSUE TITLE
Use new Minimize to support whitespace: true for whitespace in attributes

### ISSUE THREAD

**Issue by mlenser** [murphydanger/gulp-minify-html#29]
Minimize has been updated to 1.5 to support preserving whitespace in attribute values. See https://github.com/Swaagie/minimize/issues/26#issuecomment-117510475

Could you support this as well?

**Comment by mlenser** [comment]
Any ETA on deploy of this?

I assume once its out I can use it like such?
.pipe(minifyHTML({
  whitespace: true
}))

**Comment by murphydanger** [comment]
I'll publish it this afternoon. Sorry for the delay.
