### ISSUE TITLE
Mixed Language Support

### ISSUE THREAD

**Issue by virgofx** [murphydanger/gulp-minify-html#31]
I was wondering if it's possible to support .phtml files where there are interweaved PHP blocks (e.g. `<div>Hi <?php echo 'John'; ?></div>`) adjacent to the XHTML. Running the minifier against these results in some unexpected errors.

Would this be possible to ignore the contents between these language constructs?

**Comment by murphydanger** [comment]
This would be something to take up with the `Minimize` folks.
